INSERT INTO POKEMON_DTO(ID, NAME, HEIGHT_IN_CM, WEIGHT_IN_KG, OWNER) VALUES (99, 'Schiggy', 60, 6.0, 'Kristian');
INSERT INTO POKEMON_DTO(ID, NAME, HEIGHT_IN_CM, WEIGHT_IN_KG, OWNER) VALUES (100, 'Glumanda', 70, 7.0, 'Kristian');
INSERT INTO POKEMON_DTO(ID, NAME, HEIGHT_IN_CM, WEIGHT_IN_KG, OWNER) VALUES (101, 'Bisasam', 60, 6.0, 'Kristian');