INSERT INTO POKEMON_DTO(ID, NAME, HEIGHT_IN_CM, WEIGHT_IN_KG) VALUES (99, 'Schiggy', 60, 6.0);
INSERT INTO POKEMON_DTO(ID, NAME, HEIGHT_IN_CM, WEIGHT_IN_KG) VALUES (100, 'Glumanda', 70, 7.0);
INSERT INTO POKEMON_DTO(ID, NAME, HEIGHT_IN_CM, WEIGHT_IN_KG) VALUES (101, 'Bisasam', 60, 6.0);
